
// Exportamos cada const
export const PantallaInicio = {
    botonVerMas: {
        es: 'Ver más',
        en: 'Show more',
        ch: '查看更多',
        hindi: 'और देखें',
        fr: 'Voir plus',
        ara: 'عرض المزيد',
        beng: 'আরও দেখুন',
        rus: 'Смотреть больше',
        port: 'Ver mais',
        urd: 'مزید دیکھیں',
        de: 'Mehr anzeigen',
    },
    tituloTexto: {
        es: 'Comienza a explorar',
        en: 'Explore the World',
        ch: '开始探索',
        hindi: 'अन्वेषण शुरू करें',
        fr: 'Commencez à explorer',
        ara: 'ابدأ الاستكشاف',
        beng: 'অনুসন্ধান শুরু করুন',
        rus: 'Начать исследование',
        port: 'Comece a explorar',
        urd: 'تلاش شروع کریں',
        de: 'Beginnen Sie mit der Erkundung',
    },
    categoria: {
        es: 'Categoria',
        en: 'Category',
        ch: '分类',
        hindi: 'श्रेणी',
        fr: 'Catégorie',
        ara: 'الفئة',
        beng: 'বিভাগ',
        rus: 'Категория',
        port: 'Categoria',
        urd: 'زمرہ',
        de: 'Kategorie',
    },
    departamento: {
        es: 'Departamento',
        en: 'Department',
        ch: '部门',
        hindi: 'विभाग',
        fr: 'Département',
        ara: 'قسم',
        beng: 'বিভাগ',
        rus: 'Отдел',
        port: 'Departamento',
        urd: 'محکمہ',
        de: 'Abteilung',
    },
    colonial: {
        es: 'Colonial',
        en: 'Colonial',
        ch: '殖民地',
        hindi: 'कोलोनियल',
        fr: 'Colonial',
        ara: 'مستعمر',
        beng: 'কলোনিয়াল',
        rus: 'Колониальный',
        port: 'Colonial',
        urd: 'استعماری',
        de: 'Kolonial',
    },
    playas: {
        es: 'Playas',
        en: 'Beaches',
        ch: '海滩',
        hindi: 'समुद्र तट',
        fr: 'Plages',
        ara: 'شواطئ',
        beng: 'সমুদ্র সৈকত',
        rus: 'Пляжи',
        port: 'Praias',
        urd: 'ساحل',
        de: 'Strände',
    },
    bosques: {
        es: 'Bosques',
        en: 'Forests',
        ch: '森林',
        hindi: 'जंगल',
        fr: 'Forêts',
        ara: 'غابات',
        beng: 'বন',
        rus: 'Леса',
        port: 'Florestas',
        urd: 'جنگلات',
        de: 'Wälder',
    },
    museos: {
        es: 'Museos',
        en: 'Museums',
        ch: '博物馆',
        hindi: 'संग्रहालय',
        fr: 'Musées',
        ara: 'متاحف',
        beng: 'জাদুঘর',
        rus: 'Музеи',
        port: 'Museus',
        urd: 'عجائب گھر',
        de: 'Museen',
    },
    sitios: {
        es: 'Sitios Arqueológicos',
        en: 'Archaeological Sites',
        ch: '考古遗址',
        hindi: 'पुरातत्विक स्थल',
        fr: 'Sites Archéologiques',
        ara: 'مواقع أثرية',
        beng: 'ঐতিহ্যবাহী স্থল',
        rus: 'Археологические памятники',
        port: 'Sítios Arqueológicos',
        urd: 'آثاری مقامات',
        de: 'Archäologische Stätten',
    },
    balnearios: {
        es: 'Balnearios',
        en: 'Spas',
        ch: '温泉',
        hindi: 'स्पा',
        fr: 'Spas',
        ara: 'منتجعات صحية',
        beng: 'স্পা',
        rus: 'Курорты',
        port: 'Spas',
        urd: 'سپا',
        de: 'Spas',
    },
    centros: {
        es: 'Centros históricos',
        en: 'Historic center',
        ch: '历史中心',
        hindi: 'ऐतिहासिक केंद्र',
        fr: 'Centres hindistoriques',
        ara: 'مراكز تاريخية',
        beng: 'ঐতিহাসিক শহরসমূহ',
        rus: 'Исторические центры',
        port: 'Centros hindistóricos',
        urd: 'تاریخی مراکز',
        de: 'hindistorische Zentren',
    },
    todas: {
        es: 'Todas',
        en: 'All',
        ch: '所有',
        hindi: 'सभी',
        fr: 'Toutes',
        ara: 'الكل',
        beng: 'সব',
        rus: 'Все',
        port: 'Todas',
        urd: 'سب',
        de: 'Alle',
    },
    todos: {
        es: 'Todos',
        en: 'All',
        ch: '所有',
        hindi: 'सभी',
        fr: 'Tous',
        ara: 'الكل',
        beng: 'সব',
        rus: 'Все',
        port: 'Todos',
        urd: 'سب',
        de: 'Alle',
    },
    ahuachapan: {
        es: 'Ahuachapán',
        en: 'Ahuachapán',
        ch: 'Ahuachapán',
        hindi: 'अहूचापन',
        fr: 'Ahuachapán',
        ara: 'أهواتشابان',
        beng: 'আহুচাপান',
        rus: 'Ауахапан',
        port: 'Ahuachapán',
        urd: 'آہواچاپان',
        de: 'Ahuachapán',
    },
    sonsonate: {
        es: 'Sonsonate',
        en: 'Sonsonate',
        ch: '桑索纳特',
        hindi: 'सोन्सोनाते',
        fr: 'Sonsonate',
        ara: 'سونسوناتي',
        beng: 'সনসোনাতে',
        rus: 'Сонсонате',
        port: 'Sonsonate',
        urd: 'سونسونیٹ',
        de: 'Sonsonate',
    },
    santaAna: {
        es: 'Santa Ana',
        en: 'Santa Ana',
        ch: '圣安娜',
        hindi: 'सांता आना',
        fr: 'Santa Ana',
        ara: 'سانتا آنا',
        beng: 'সান্তা আনা',
        rus: 'Санта-Ана',
        port: 'Santa Ana',
        urd: 'سانتا آنا',
        de: 'Santa Ana',
    },
    chalatenango: {
        es: 'Chalatenango',
        en: 'Chalatenango',
        ch: '查拉特南戈',
        hindi: 'चालातेनंगो',
        fr: 'Chalatenango',
        ara: 'تشالاتينانجو',
        beng: 'চালাটেনাঙ্গো',
        rus: 'Чалатенанго',
        port: 'Chalatenango',
        urd: 'چالاٹینانگو',
        de: 'Chalatenango',
    },
    laLibertad: {
        es: 'La Libertad',
        en: 'La Libertad',
        ch: '拉利伯塔德',
        hindi: 'ला लिबर्टाद',
        fr: 'La Libertad',
        ara: 'لا ليبرتاد',
        beng: 'লা লিবার্ট্যাড',
        rus: 'Ла-Либертад',
        port: 'La Libertad',
        urd: 'لا لبرٹیڈ',
        de: 'La Libertad',
    },
    sanSalvador: {
        es: 'San Salvador',
        en: 'San Salvador',
        ch: '圣萨尔瓦多',
        hindi: 'सैन सैल्वाडोर',
        fr: 'San Salvador',
        ara: 'سان سلفادور',
        beng: 'সান সালভাদোর',
        rus: 'Сан-Сальвадор',
        port: 'San Salvador',
        urd: 'سان سلوادور',
        de: 'San Salvador',
    },
    laPaz: {
        es: 'La Paz',
        en: 'La Paz',
        ch: '拉巴斯',
        hindi: 'ला पाज़',
        fr: 'La Paz',
        ara: 'لا باز',
        beng: 'লা পাজ',
        rus: 'Ла-Пас',
        port: 'La Paz',
        urd: 'لا پاز',
        de: 'La Paz',
    },
    cabanas: {
        es: 'Cabañas',
        en: 'Cabañas',
        ch: '卡瓦尼亚斯',
        hindi: 'काबानास',
        fr: 'Cabañas',
        ara: 'كابانياس',
        beng: 'কাবানাস',
        rus: 'Кабаньяс',
        port: 'Cabañas',
        urd: 'کاباناس',
        de: 'Cabañas',
    },
    sanVicente: {
        es: 'San Vicente',
        en: 'San Vicente',
        ch: '圣维森特',
        hindi: 'सैन विसेंट',
        fr: 'San Vicente',
        ara: 'سان فيسنتي',
        beng: 'সান ভিসেন্টে',
        rus: 'Сан-Висенте',
        port: 'San Vicente',
        urd: 'سان ویسینٹ',
        de: 'San Vicente',
    },
    usulutan: {
        es: 'Usulután',
        en: 'Usulután',
        ch: '乌苏卢坦',
        hindi: 'उसुलुटान',
        fr: 'Usulután',
        ara: 'أوسولوتان',
        beng: 'উসুলুতান',
        rus: 'Усулутан',
        port: 'Usulután',
        urd: 'اوسولوٹان',
        de: 'Usulután',
    },
    sanMiguel: {
        es: 'San Miguel',
        en: 'San Miguel',
        ch: '圣米格尔',
        hindi: 'सैन मिगेल',
        fr: 'San Miguel',
        ara: 'سان ميغيل',
        beng: 'সান মিগুয়েল',
        rus: 'Сан-Мигель',
        port: 'San Miguel',
        urd: 'سان میگوئل',
        de: 'San Miguel',
    },
    morazan: {
        es: 'Morazán',
        en: 'Morazán',
        ch: '莫拉桑',
        hindi: 'मोराज़ान',
        fr: 'Morazán',
        ara: 'مورازان',
        beng: 'মোরাজান',
        rus: 'Морасан',
        port: 'Morazán',
        urd: 'مورازان',
        de: 'Morazán',
    },
    laUnion: {
        es: 'La Unión',
        en: 'La Unión',
        ch: '拉乌尼翁',
        hindi: 'ला यूनियन',
        fr: 'La Unión',
        ara: 'لا اتحاد',
        beng: 'লা ইউনিয়ন',
        rus: 'Ла-Унион',
        port: 'La Unión',
        urd: 'لا یونین',
        de: 'La Unión',
    },
    cuscatlan: {
        es: 'Cuscatlán',
        en: 'Cuscatlán',
        ch: '库斯卡特兰',
        hindi: 'कुस्कातलान',
        fr: 'Cuscatlán',
        ara: 'كوسكاتلان',
        beng: 'কুসকাটলান',
        rus: 'Кускатлан',
        port: 'Cuscatlán',
        urd: 'کسکٹلان',
        de: 'Cuscatlán',
    },
    mensaje: {
        es: 'No se ha encontrado ningún resultado en su búsqueda.',
        en: 'No result has been found for your search.',
        ch: '没有找到您的搜索结果。',
        hindi: 'आपके खोज के लिए कोई परिणाम नहीं मिला।',
        fr: 'Aucun résultat trouvé pour votre recherche.',
        ara: 'لم يتم العثور على نتائج لبحثك.',
        beng: 'আপনার অনুসন্ধানের জন্য কোনও ফলাফল পাওয়া যায়নি।',
        rus: 'По вашему запросу ничего не найдено.',
        port: 'Nenhum resultado foi encontrado paraaa a sua busca.',
        urd: 'آپ کے تلاش کے لئے کوئی نتائج نہیں ملے۔',
        de: 'Es wurden keine Ergebengisse für Ihre Suche gefunden.',
    },
    advertencia: {
        es: 'Advertencia',
        en: 'Warning',
        ch: '警告',
        hindi: 'चेतावनी',
        fr: 'Avertissement',
        ara: 'تحذير',
        beng: 'সতর্কতা',
        rus: 'Предупреждение',
        port: 'Advertência',
        urd: 'اخطار',
        de: 'Warnung'
    },

    mensajeDeAdvertencia: {
        es: 'No se ha encontrado ningún resultado',
        en: 'No results have been found',
        ch: '没有找到结果',
        hindi: 'कोई परिणाम नहीं मिला',
        fr: 'Aucun résultat trouvé',
        ara: 'لم يتم العثور على أي نتائج',
        beng: 'কোনও ফলাফল পাওয়া যায়নি',
        rus: 'Результаты не найдены',
        port: 'Nenhum resultado foi encontrado',
        urd: 'کوئی نتائج نہیں ملے',
        de: 'Es wurden keine Ergebnisse gefunden'
    },
    mensajeEliminar: {
        es: 'Se eliminó de favoritos',
        en: 'Removed from favorites',
        ch: '已从收藏夹中删除',
        hindi: 'पसंदीदा से हटा दिया गया',
        fr: 'Retiré des favoris',
        ara: 'تمت إزالته من المفضلة',
        beng: 'পছন্দ থেকে সরানো হয়েছে',
        rus: 'Удалено из избранного',
        port: 'Removido dos favoritos',
        urd: 'پسندیدگی سے ہٹا دیا گیا',
        de: 'Aus Favoriten entfernt'
    },
    mensajeAgregar: {
        es: 'Se agregó a favoritos',
        en: 'Added to favorites',
        ch: '已添加到收藏夹',
        hindi: 'पसंदीदा में जोड़ा गया',
        fr: 'Ajouté aux favoris',
        ara: 'تمت الإضافة إلى المفضلة',
        beng: 'পছন্দে যোগ করা হয়েছে',
        rus: 'Добавлено в избранное',
        port: 'Adicionado aos favoritos',
        urd: 'پسندیدہ میں شامل کیا گیا',
        de: 'Zu Favoriten hinzugefügt'
    },    
};
