

export default function ServicesCategoriesPriceIdiom() {


    const priceList = [
        {
            id: 1,
            name: 'General',
        },
        {
            id: 2,
            name: 'Niños',
        },
        {
            id: 3,
            name: 'Adulto',
        },
        {
            id: 4,
            name: 'Parqueo',
        },
        {
            id: 5,
            name: 'Estudiantes',
        },
        {
            id: 6,
            name: 'Tercera Edad',
        },
        {
            id: 7,
            name: 'Discapacitados',
        },
        {
            id: 8,
            name: 'Otros',
        }
    ];

    const PriceIdiom = {
        1: {
            es: "General",
            en: "General",
            ch: "一般",
            hindi: "सामान्य",
            fr: "Général",
            ara: "جنرال",
            beng: "সাধারণ",
            rus: "генеральный",
            port: "Geral",
            urd: "جنرل",
            de: "Allgemeines",
        },
        2: {
            es: "Niños",
            en: "Children",
            ch: "孩子",
            hindi: "बच्चे",
            fr: "Enfants",
            ara: "أطفال",
            beng: "শিশুরা",
            rus: "дети",
            port: "Crianças",
            urd: "بچے",
            de: "Kinder",
        },
        3: {
            es: "Adulto",
            en: "Adult",
            ch: "成人",
            hindi: "वयस्क",
            fr: "Adulte",
            ara: "بالغ",
            beng: "প্রাপ্তবয়স্ক",
            rus: "взрослый",
            port: "Adulto",
            urd: "بالغ",
            de: "Erwachsener",
        },
        4: {
            es: "Parqueo",
            en: "Parking",
            ch: "停车",
            hindi: "पार्किंग",
            fr: "Parking",
            ara: "موقف سيارات",
            beng: "পার্কিং",
            rus: "парковка",
            port: "Estacionamento",
            urd: "پارکنگ",
            de: "Parken",
        },
        5: {
            es: "Estudiantes",
            en: "Students",
            ch: "学生",
            hindi: "छात्र",
            fr: "Étudiants",
            ara: "طلاب",
            beng: "ছাত্র",
            rus: "студенты",
            port: "Estudantes",
            urd: "طلبہ",
            de: "Studenten",
        },
        6: {
            es: "Tercera Edad",
            en: "Third Age",
            ch: "第三年龄",
            hindi: "तीसरी आयु",
            fr: "Troisième âge",
            ara: "العمر الثالث",
            beng: "তৃতীয় বয়স্ক",
            rus: "третий возраст",
            port: "Terceira idade",
            urd: "تیسری عمر",
            de: "Drittes Alter",
        },
        7: {
            es: "Discapacitados",
            en: "Disabled",
            ch: "残疾人",
            hindi: "विकलांग",
            fr: "Handicapé",
            ara: "معاق",
            beng: "প্রতিবন্ধী",
            rus: "инвалид",
            port: "Deficiente",
            urd: "معذور",
            de: "Behinderte",
        },
        8: {
            es: "Otros",
            en: "Others",
            ch: "其他",
            hindi: "अन्य",
            fr: "Autres",
            ara: "آخرين",
            beng: "অন্যান্য",
            rus: "другие",
            port: "Outros",
            urd: "دیگر",
            de: "Andere",
        }
    }

    const categoriesList = [{
        id: 1,
        name: 'Colonial',
    },
    {
        id: 2,
        name: 'Playas'
    },
    {
        id: 3,
        name: 'Bosques'
    },
    {
        id: 4,
        name: 'Sitios Arqueológicos'
    },
    {
        id: 5,
        name: 'Museos'
    },
    {
        id: 6,
        name: 'Balnearios'
    },
    {
        id: 7,
        name: 'Otros'
    }];
    const CategoriesIdiom = {
        1: {
            es: "Colonial",
            en: "Colonial",
            ch: "殖民地",
            hindi: "कोलोनियल",
            fr: "Colonial",
            ara: "مستعمرة",
            beng: "কলোনিয়াল",
            rus: "колониальный",
            port: "Colonial",
            urd: "کولونیل",
            de: "Kolonial",
        },
        2: {
            es: "Playas",
            en: "Beaches",
            ch: "海滩",
            hindi: "समुद्र तट",
            fr: "Plages",
            ara: "شواطئ",
            beng: "সমুদ্র সৈকত",
            rus: "пляжи",
            port: "Praias",
            urd: "ساحل",
            de: "Strände",
        },
        3: {
            es: "Bosques",
            en: "Forests",
            ch: "森林",
            hindi: "जंगल",
            fr: "Forêts",
            ara: "غابات",
            beng: "বন",
            rus: "леса",
            port: "Florestas",
            urd: "جنگلات",
            de: "Wälder",
        },
        4: {
            es: "Sitios Arqueológicos",
            en: "Archaeological sites",
            ch: "考古遗址",
            hindi: "पुरातात्विक स्थल",
            fr: "Sites archéologiques",
            ara: "مواقع أثرية",
            beng: "পুরাতত্ত্বিক স্থান",
            rus: "археологические памятники",
            port: "Sítios arqueológicos",
            urd: "تاریخی مقامات",
            de: "Archäologische Stätten",
        },
        5: {
            es: "Museos",
            en: "Museums",
            ch: "博物馆",
            hindi: "संग्रहालय",
            fr: "Musées",
            ara: "متاحف",
            beng: "জাদুঘর",
            rus: "музеи",
            port: "Museus",
            urd: "عجائب گھر",
            de: "Museen",
        },
        6: {
            es: "Balnearios",
            en: "Spas",
            ch: "温泉",
            hindi: "स्पा",
            fr: "Spas",
            ara: "منتجعات صحية",
            beng: "স্পা",
            rus: "спа",
            port: "Spas",
            urd: "سپا",
            de: "Spas",
        },
        7: {
            es: "Otros",
            en: "Others",
            ch: "其他",
            hindi: "अन्य",
            fr: "Autres",
            ara: "آخرين",
            beng: "অন্যান্য",
            rus: "другие",
            port: "Outros",
            urd: "دیگر",
            de: "Andere",
        },
        8: {
            es: "Todas",
            en: "All",
            ch: "所有",
            hindi: "सभी",
            fr: "Toutes",
            ara: "الجميع",
            beng: "সব",
            rus: "Все",
            port: "Todos",
            urd: "سب",
            de: "Alle",
        }
        
    }
    const servicesList = [
        {
            id: 1,
            name: 'Parqueo',
        },
        {
            id: 2,
            name: 'Restaurantes',
        },
        {
            id: 3,
            name: 'Hospedaje',
        },
        {
            id: 4,
            name: 'Miradores',
        },
        {
            id: 5,
            name: 'Atencion Medica',
        },
        {
            id: 6,
            name: 'Entretenimiento',
        },
        {
            id: 7,
            name: 'Salas de Belleza',
        },
        {
            id: 8,
            name: 'Servicios Financieros',
        },
        {
            id: 9,
            name: 'Centro Religioso',
        },
        {
            id: 10,
            name: 'Centros Historicos',
        },
        {
            id: 11,
            name: 'Balneario',
        },
        {
            id: 12,
            name: 'Gimnasia',
        },
        {
            id: 13,
            name: 'Mercado de Artesa.',
        },
        {
            id: 14,
            name: 'Boutique',
        },
    ];

    const ServiciosIdiom = {
        1: {
            es: "Parqueo",
            en: "Parking",
            ch: "停车",
            hindi: "पार्किंग",
            fr: "Parking",
            ara: "موقف سيارات",
            beng: "পার্কিং",
            rus: "парковка",
            port: "Estacionamento",
            urd: "پارکنگ",
            de: "Parken",
        },
        2: {
            es: "Restaurantes",
            en: "Restaurants",
            ch: "餐馆",
            hindi: "रेस्टोरेंट",
            fr: "Restaurants",
            ara: "مطاعم",
            beng: "রেস্তোরাঁ",
            rus: "рестораны",
            port: "Restaurantes",
            urd: "ریستوراں",
            de: "Restaurants",
        },
        3: {
            es: "Hospedaje",
            en: "Lodging",
            ch: "住宿",
            hindi: "आवास",
            fr: "Hébergement",
            ara: "إقامة",
            beng: "আবাস",
            rus: "жилье",
            port: "Alojamento",
            urd: "لوجنگ",
            de: "Unterkunft",
        },
        4: {
            es: "Miradores",
            en: "Viewpoints",
            ch: "观景台",
            hindi: "दृश्य बिंदु",
            fr: "Points de vue",
            ara: "مناظر طبيعية",
            beng: "দৃশ্যদানকারী",
            rus: "видовые площадки",
            port: "Miradouros",
            urd: "دریافت نقطہ",
            de: "Aussichtspunkte",
        },
        5: {
            es: "Atencion Medica",
            en: "Medical attention",
            ch: "医疗",
            hindi: "चिकित्सा ध्यान",
            fr: "Attention médicale",
            ara: "الرعاية الطبية",
            beng: "চিকিৎসা বিষয়ক দৃষ্টিকোণ",
            rus: "медицинское внимание",
            port: "Atenção médica",
            urd: "طبی توجہ",
            de: "Medizinische Versorgung",
        },
        6: {
            es: "Entretenimiento",
            en: "Entertainment",
            ch: "娱乐",
            hindi: "मनोरंजन",
            fr: "Divertissement",
            ara: "ترفيه",
            beng: "বিনোদন",
            rus: "развлечения",
            port: "Entretenimento",
            urd: "تفریح",
            de: "Unterhaltung",
        },
        7: {
            es: "Salas de Belleza",
            en: "Beauty salons",
            ch: "美容院",
            hindi: "सौंदर्य सैलून",
            fr: "Salons de beauté",
            ara: "صالونات التجميل",
            beng: "সৌন্দর্য সেলুন",
            rus: "салоны красоты",
            port: "Salões de beleza",
            urd: "خوبصورتی سیلون",
            de: "Schönheitssalons",
        },
        8: {
            es: "Servicios Financieros",
            en: "Financial services",
            ch: "金融服务",
            hindi: "वित्तीय सेवाएं",
            fr: "Services financiers",
            ara: "الخدمات المالية",
            beng: "আর্থিক সেবা",
            rus: "финансовые услуги",
            port: "Serviços financeiros",
            urd: "مالی خدمات",
            de: "Finanzdienstleistungen",
        },
        9: {
            es: "Centro Religioso",
            en: "Religious center",
            ch: "宗教中心",
            hindi: "धार्मिक केंद्र",
            fr: "Centre religieux",
            ara: "مركز ديني",
            beng: "ধর্মীয় কেন্দ্র",
            rus: "религиозный центр",
            port: "Centro religioso",
            urd: "مذہبی مرکز",
            de: "Religiöses Zentrum",
        },
        10: {
            es: "Centros Historicos",
            en: "Historical centers",
            ch: "历史中心",
            hindi: "ऐतिहासिक केंद्र",
            fr: "Centres historiques",
            ara: "المراكز التاريخية",
            beng: "ঐতিহাসিক কেন্দ্র",
            rus: "исторические центры",
            port: "Centros históricos",
            urd: "تاریخی مراکز",
            de: "Historische Zentren",
        },
        11: {
            es: "Balneario",
            en: "Spa",
            ch: "水疗中心",
            hindi: "स्पा",
            fr: "Spa",
            ara: "منتجع صحي",
            beng: "স্পা",
            rus: "спа",
            port: "Spa",
            urd: "سپا",
            de: "Spa",
        },
        12: {
            es: "Gimnasia",
            en: "Gymnastics",
            ch: "体操",
            hindi: "जिम्नास्टिक",
            fr: "Gymnastique",
            ara: "الجمباز",
            beng: "জিমনাস্টিক",
            rus: "гимнастика",
            port: "Ginástica",
            urd: "جمناسٹکس",
            de: "Gymnastik",
        },
        13: {
            es: "Mercado de Artesa.",
            en: "Craft market",
            ch: "工艺品市场",
            hindi: "क्राफ्ट बाजार",
            fr: "Marché artisanal",
            ara: "سوق الحرف",
            beng: "ক্রাফট বাজার",
            rus: "ремесленный рынок",
            port: "Mercado de artesanato",
            urd: "کرافٹ مارکیٹ",
            de: "Handwerksmarkt",
        },
        14: {
            es: "Boutique",
            en: "Boutique",
            ch: "精品店",
            hindi: "बुटीक",
            fr: "Boutique",
            ara: "متجر",
            beng: "বুটিক",
            rus: "бутик",
            port: "Boutique",
            urd: "بوتیک",
            de: "Boutique",
        }
    }

    return {
        priceList,
        PriceIdiom,
        categoriesList,
        CategoriesIdiom,
        servicesList,
        ServiciosIdiom
    }
}